### ISSUE TITLE
w_truncate results in wrong parent/child connectivity info in the h5 file 

### ISSUE THREAD

**Issue by ASinanSaglam** [westpa/west_tools#4] opened 2015-03-30 17:59 UTC
Simulations are left with wrong connectivity info after a truncation. 

If physical sym-linking is done the child/parents are incorrectly linked in the h5file but correctly linked in the file system meaning the environment variables are set correctly and parent/child are correctly linked but written incorrectly in the main h5 file. This results in continuous trajectories but messed up probabilities from what I can tell since the probabilities are incorrectly assigned for the next iteration. 

The issue might not be directly linked to w_truncate but that's when I saw the issue, it might be that the simulation doesn't overwrite previous connectivity later down in the simulation pipeline.

**Comment by synapticarbors** [comment] 2015-03-30 18:05
@ASinanSaglam What do you mean by "physical sym-linking" here? I'm a little confused since `w_truncate` just removes whole iteration groups from the h5 file and doesn't write any new information into that file except modifying the `current_iteration`.

**Comment by ASinanSaglam** [comment] 2015-03-30 18:16
Basically making sym-links in the file system (physical was a terrible word choice there!) in the runseg from parent to child (for pulling previous coordinate/trajectory files for example). I wrote a small python script that crawls back up to the 1st iteration parent starting from a child using both the h5 file and the sym-links in the file system and they don't mach at certain iterations.

**Comment by synapticarbors** [comment] 2015-03-30 18:27
I'm still confused about the exact use-case and what's going on here. When you use `w_truncate` you should consider any iterations after the truncation point invalid in terms of on-disk data in `traj_segs`. 

Are you saying that when you truncate a run and then restart it, then sometime later when you traverse the whole split/merge tree, there are inconsistencies? Again, this shouldn't happen since `w_truncate` doesn't modify any iteration data; it just removes full iterations. Is it possible that a completed segment in a truncated iteration has some symlink written and then it just doesn't get over-written when that segment is re-run? Do you see the same problem if you truncate the h5 file and also delete the corresponding iteration directories in `traj_segs`? What are these symlinks being used for?

**Comment by ASinanSaglam** [comment] 2015-03-30 18:36
Exactly the case you described in the second paragraph. 

To shine a bit more light on the situation I'll describe what happened: I had a simulation that I truncated at iteration, say 195 onward. I moved the physical files of iteration 195 off the traj_segs, restart the simulation. Simulation generates a new iteration 195 and moves forward. When I trace the parent/child relationship from the child upwards I end up with a disconnect at iteration 195, the sym-link tells me the parent is iteration 194/walker 10, the h5 tells me it's iteration 194/walker 90 for example (numbers made up here, can give more specifics if you prefer). And of course as expected only the sym-link trace makes physical sense. 

As far as I remember I moved the iteration data off every time I truncated, symlinks are there for the coordinates and the velocities for the next walker. It would make sense that ln -s didn't create a new symlink for the files that are already there if I didn't move them but I'm fairly certain I did.

**Comment by ajoshpratt** [comment] 2015-03-30 18:43
I'm running some tests on this now in order to validate exactly what is going on.  While I normally do move iteration data when I truncate, I forgot to do so during this test and so am rerunning the test to eliminate that factor.

Here's how I set up the test: I symlinked in the parent structure so that I would have a record of what segment the parent was.

Looking at the h5 file does suggest there's a problem here, however: in the test simulation I have, in the iteration I truncated, the on file system parent-child linkage and the in h5 parent-child linkage do not agree; moreover, the last timepoint of the progress coordinate of the h5 parent does not match up with the 0th time point of the progress coordinate of the child, whereas if I look at the parent that the file system gives me, the progress coordinates do indeed match up.

**Comment by ajoshpratt** [comment] 2015-03-30 18:47
@synapticarbors, I'm running some tests on a model system to determine what's going on now.  I'll update when I'm done running them.

**Comment by synapticarbors** [comment] 2015-03-30 18:49
Am I correct in assuming that the symlink is only for some sort of post-production analysis/visualization, and the links aren't actually used to run the WE simulation?

Maybe @mczwier has some ideas about this, but it seems very strange to me. Every iteration should be atomic, so there shouldn't be a difference when a simulation re-starts after truncation vs restarts just to extend a previously halted simulation. WESTPA shouldn't even be able to tell the difference between those two scenarios. 

@ajoshpratt I'll be interested to see what the tests turn up.

**Comment by mczwier** [comment] 2015-03-30 19:00
Yes, @synapticarbors has it. Each iteration is atomic. After truncation, WE is run *again* to restart the next iteration, so there is no guarantee that the same parent-child links are present in the newly-run iteration. It is statistically correct, but not binary identical.

As a result, you should blow away all filesystem data associated with truncated iterations. Wholesale. Leave nothing behind. The problem you're describing comes from ``ln`` refusing to overwrite existing symlinks, which would be avoided if the segment directory you're overwriting instead didn't exist.

@ASinanSaglam: can you confirm that what I've described is indeed what is going on (check your seg logs, or as an extreme ensure that failure to create symlinks, as seems to be happening silently here, crashes runseg with an error). If so, I propose closing this, though definitely this should be addressed in simulation "best practices" documentation.

**Comment by ajoshpratt** [comment] 2015-03-30 19:06
Failure to blow away the data does indeed result in incorrect parent-child linkages, whereas everything is kosher if you move the iteration data.

I encouraged @ASinanSaglam to post this bug report, as I'd screwed up my own test without realising it (normally, I blow away the data after using w_truncate; however, of course, while testing this before suggesting he post it as a bug report, I forgot to do so).  Go figure.

As a general rule, if something is "mission critical" for a tool, should we consider integrating it into the docstrings so that an end user might not forget it when they're using the tool?

**Comment by ASinanSaglam** [comment] 2015-03-30 19:06
The links are required for the propagation of the simulation since the next walker needs the previous walkers coordinates, velocities and thermostat/barostat data (namely the gro, xtc and the edr files). So it is used in the simulation directly. 

Also as I have mentioned before, this might not have anything to do with w_truncate, it was just an instance where I saw the error and suspected truncation since I had some issues with Frank and had to truncate a few times (simulation wouldn't run after dying in the queue for example, especially after Frank was brought back up from maintenance). I actually don't think I truncated every time I'm seeing this error but I can't remember since it's been more than 3 months since I ran this simulation. 

I would agree that if I left he links there this would be the resulting issue though, I'm checking the seg_logs now for a particular instance. I agree with closing the issue as well since I can't remember if I truncated or not at that particular iteration, I will just post another one if I can regenerate the problem since then it would not be related to w_truncate. I will also run " sed -i 's/ln -sv/ln -svf/' " on my runseg.sh just in case I mess up on that next time.

**Comment by synapticarbors** [comment] 2015-03-30 19:19
@ASinanSaglam But aren't the symlinks being created using `$WEST_PARENT_DATA_REF` in the current iteration? Unless there is something fundamentally broken in westpa, then that environ variable should always match what is in the h5 file. I think it's likely that the issue is old symlinks not being over written, but if you can re-create this when completely deleting all iteration data from truncated iterations, then we should take a closer look.

**Comment by ASinanSaglam** [comment] 2015-03-30 19:30
@synapticarbors Yes I fully agree with that, that does sound like the most likely scenario but I both don't think I left them in there after a truncation and can't seem to find the issue in my seg_logs ( @mczwier ln doesn't seem to complain there with set -x and should give a file exists error I'm sure). Regardless, I now think this is a case where I either forgot the last iteration data in there and didn't overwrite the symlinks or the issue I had was somewhere else. In both cases I think we can close the issue since it's not related to w_truncate. 

Sorry to take your time all! Thanks for the quick responses!

**Comment by mczwier** [comment] 2015-03-31 14:12
No problem Ali. This was a good discussion to have. Sounds like this is a system-level issue (when ``ln -s`` fails, or fails to fail).

**Closed** 2015-03-31 14:13 UTC
Labels: invalid

**Comment by synapticarbors** [comment] 2015-03-31 14:38
@mczwier I was going to add an message to `w_truncate` that says the following:

>NOTE: w_truncate only deletes iteration groups from the HDF5 data store.
It is recommended that any iteration data saved to the file system (e.g. in the
traj_segs directory) is deleted or moved for the corresponding iterations.

Any wording or format changes? Also, do you prefer to have it as a warning message after the program runs, or in the `-h` description?

**Comment by mczwier** [comment] 2015-03-31 14:42
Ah, very nice. I think it should be in both places. What do you think?
